server:
  port: 8082

spring:
  application:
     name: accounts-service
  jpa:
     hibernate:
        ddl-auto: update

security:
  basic:
    enabled: false

logging:
  level:
     io:
        pivotal: DEBUG
     com:
        netflix: DEBUG
     org:
        springframework:
           web: DEBUG
           cloud: 
             sleuth:
               log: WARN    
                            
