logging:
  level:
     io:
        pivotal: DEBUG
     com:
        netflix: DEBUG
     org:
        springframework:
           web: DEBUG
           cloud: DEBUG
             sleuth:
               log: WARN
