eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
pivotal:
  quotesService:
    name: quotes-service
  accountsService:
    name: accounts-service
  portfolioService:
    name: portfolio-service
logging:
  level:
     io:
        pivotal: DEBUG
     com:
        netflix: WARN
     org:
        springframework:
           web: WARN
           cloud: WARN
