eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    nonSecurePort: ${server.port}
management:
  health:
    rabbit:
      enabled: false
logging:
  level:
     io:
        pivotal: DEBUG
     com:
        netflix: INFO
     org:
        springframework:
           web: WARN
           cloud: INFO
