ribbon:
  IsSecure: false

pivotal:
  quotesService:
    name: quotes-service
  accountsService:
    name: accounts-service
  portfolioService:
    name: portfolio-service

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([trace=%X{X-Trace-Id:-},span=%X{X-Span-Id:-}]){yellow} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%replace(%xException){'\n','\u2028'}%nopex%n"
  level:
     io:
        pivotal: DEBUG
     com:
        netflix: FATAL
     org:
        springframework:
           web: DEBUG
           cloud: DEBUG

eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    nonSecurePort: ${server.port}
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

management:
  health:
    db.enabled: false
    rabbit.enabled: false
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  sleuth:
    sampler:
      probability: 0.1

 zuul:
  ignoredServices: '*'
  routes:
    quotes-service: /quotes-service/**
    accounts-service: /accounts-service/***
    portfolio-service: /portfolio-service/***

---
spring:
  profiles: cloud
  cloud:
    services:
      registrationMethod: route
      
eureka:
  instance:
     nonSecurePort: ${PORT:80}

server:
  port: ${PORT:80}       
                  
