spring:
  application:
     name: quotes-service
pivotal:
  quotes:
    quotes_url: http://dev.markitondemand.com/Api/v2/Quote/json?symbol={symbol}
    companies_url: http://dev.markitondemand.com/Api/v2/Lookup/json?input={name}
security:
  basic:
    enabled: false
