server:
  port: 8080

spring:
  application:
     name: web-service
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
     
eureka:
  client:
    registerWithEureka: true
    registryFetchIntervalSeconds: 10

pivotal:
  summary:
    quotes: 3
    symbols:
      it: ORCL,IBM,INTC,AMD,HPQ,CSCO,AAPL
      fs: JPM,C,MS,BAC,GS,WFC,BK
